services:
  - type: web
    name: biology-chatbot
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: NLTK_DATA
        value: /opt/render/.cache/nltk_data
    plan: free